extends: spectral:oas

rules:
  # Keep CI usable while iterating
  info-description: off
  operation-description: warn
  operation-operationId-unique: error
  operation-parameters: warn
  operation-success-response: warn
  openapi-tags: warn
  no-unresolved-refs: error
