extends:
  - spectral:oas
  - spectral:recommended

rules:
  # Keep CI usable while iterating
  info-description: off
  info-contact: off
  operation-description: warn
  operation-operationId-unique: error
  operation-parameters: warn
  operation-success-response: warn
  openapi-tags: warn
