name: Apps Script CI

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'appsscript.json'
      - '.clasp.json'
      - 'scripts/update-webapp.mjs'
      - '.github/workflows/ci-appsscript.yml'

concurrency:
  group: apps-script-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Configure clasp authentication
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          if [ -z "$CLASPRC_JSON" ]; then
            echo "CLASPRC_JSON secret is required"
            exit 1
          fi
          printf '%s' "$CLASPRC_JSON" > "$HOME/.clasprc.json"

      - name: Verify clasp status
        run: npx clasp status

      - name: Push project source
        run: npx clasp push --force

      - name: Update existing Web App deployment
        run: node scripts/update-webapp.mjs
